wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1682268635
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.5
      5: 0.12.21
      6: 4.20.1
      8:
      - 5
